"""Stage 2 training loop for WhisperMamba (ASR fine-tuning).

Loss: cross-entropy on next transcript token.
Frozen: encoder, token/position embeddings (set in WhisperMambaStudent.__init__).
Trained: SSM layers, cross-attention, FFN, layer norms.

Scheduled Sampling (key addition):
  Pure teacher forcing teaches the model to predict token t+1 given the correct
  token t — but at inference it sees its OWN (possibly wrong) token t instead.
  Scheduled sampling fixes this by gradually replacing ground-truth tokens with
  the model's own predictions during training:

    p(step) = ss_max_p * min(1, step / (total_steps / 2))

  At step 0:          p=0.00  → 100% teacher-forced (same as before)
  At 50% of training: p=ss_max_p  → stays there for second half
  Default ss_max_p=0.5 means 50% of tokens are self-generated by end.

  Implementation: one no-grad forward pass to get predictions, then build
  mixed decoder_input_ids, then the actual training forward + backward.

Logging (TensorBoard):
  train/loss       — per-step cross-entropy
  train/lr         — learning rate
  train/ss_p       — scheduled sampling probability (watch it ramp up)
  val/loss         — teacher-forced val cross-entropy
  val/wer          — word error rate (the real ASR metric)
"""
import math
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
from pathlib import Path
from datetime import datetime
from tqdm import tqdm


# ── Validation helpers ────────────────────────────────────────────────────────

@torch.no_grad()
def compute_val_loss(
    model, val_loader: DataLoader, device: str, max_batches: int = 30
) -> float:
    """Teacher-forced cross-entropy — convergence check, not a final ASR metric."""
    model.eval()
    total_loss, count = 0.0, 0

    for i, batch in enumerate(val_loader):
        if i >= max_batches:
            break
        input_features = batch["input_features"].to(device)
        labels = batch["labels"].to(device)

        bos = torch.full(
            (labels.shape[0], 1),
            model.config.decoder_start_token_id,
            dtype=torch.long,
            device=device,
        )
        decoder_input_ids = torch.cat([bos, labels[:, :-1].clamp(min=0)], dim=1)

        out = model(input_features=input_features, decoder_input_ids=decoder_input_ids)
        loss = F.cross_entropy(
            out.logits.reshape(-1, out.logits.size(-1)),
            labels.reshape(-1),
            ignore_index=-100,
        )
        if torch.isfinite(loss):
            total_loss += loss.item()
            count += 1

    model.train()
    return total_loss / max(count, 1)


@torch.no_grad()
def compute_wer(
    model,
    val_loader: DataLoader,
    processor,
    device: str,
    max_batches: int = 20,
) -> float | None:
    """WER — the real ASR metric. Autoregressive generation, no teacher forcing."""
    try:
        import jiwer
    except ImportError:
        return None

    model.eval()
    all_preds, all_refs = [], []

    for i, batch in enumerate(val_loader):
        if i >= max_batches:
            break
        input_features = batch["input_features"].to(device)
        labels = batch["labels"]

        predicted_ids = model.generate(
            input_features,
            language="en",
            task="transcribe",
            max_new_tokens=128,
            repetition_penalty=1.1,
        )
        preds = processor.batch_decode(predicted_ids, skip_special_tokens=True)
        refs = processor.batch_decode(labels.clamp(min=0), skip_special_tokens=True)
        all_preds.extend(preds)
        all_refs.extend(refs)

    model.train()
    return jiwer.wer(all_refs, all_preds) if all_refs else None


# ── Scheduled sampling ────────────────────────────────────────────────────────

def _build_mixed_decoder_input(
    student_model,
    input_features: torch.Tensor,
    decoder_input_ids: torch.Tensor,
    p: float,
    device: str,
) -> torch.Tensor:
    """Replace ground-truth decoder tokens with model predictions with prob p.

    decoder_input_ids: (B, L) = [BOS, label_0, label_1, ..., label_{L-2}]

    At position t+1, the model predicted token t+1 from position t.
    We replace decoder_input_ids[:, t+1] with that prediction with prob p.

    Returns mixed_decoder_input_ids: (B, L)
    """
    if p <= 0.0:
        return decoder_input_ids

    B, L = decoder_input_ids.shape

    # One no-grad forward pass to get per-position predictions
    with torch.no_grad():
        out = student_model(
            input_features=input_features,
            decoder_input_ids=decoder_input_ids,
        )
    # pred_tokens[:, t] = model's prediction for position t+1
    pred_tokens = out.logits.argmax(-1).clamp(min=0)  # (B, L)

    # Sample a binary mask: True → use model's prediction at that position
    # Shape (B, L-1) for positions 1..L-1 (never replace BOS at position 0)
    use_pred = torch.bernoulli(
        torch.full((B, L - 1), p, device=device)
    ).bool()

    mixed = decoder_input_ids.clone()
    # positions 1..L-1 in decoder_input_ids ↔ pred_tokens[:, 0..L-2]
    mixed[:, 1:] = torch.where(
        use_pred,
        pred_tokens[:, :-1],
        decoder_input_ids[:, 1:],
    )
    return mixed


# ── Training loop ─────────────────────────────────────────────────────────────

def train_whisper_mamba(
    student_model,
    train_loader: DataLoader,
    val_loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    processor=None,
    device: str = "cpu",
    epochs: int = 5,
    checkpoint_dir: str = "./checkpoints/whisper_mamba",
    tb_log_dir: str | None = None,
    log_every: int = 50,
    eval_every: int = 500,
    wer_every: int = 1000,
    scheduler=None,
    ss_max_p: float = 0.5,
) -> list[float]:
    """Stage 2: end-to-end ASR fine-tuning with scheduled sampling.

    Args:
        processor:  WhisperProcessor — needed for WER decoding.
        wer_every:  Log WER every N steps (expensive — autoregressive).
        ss_max_p:   Max scheduled sampling probability (0 = pure teacher forcing,
                    0.5 = 50% self-generated tokens by mid-training).
    """
    checkpoint_dir = Path(checkpoint_dir)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    run_name = datetime.now().strftime("whisper_stage2_%Y%m%d_%H%M%S")
    log_dir = Path(tb_log_dir) / run_name if tb_log_dir else Path("runs") / run_name
    writer = SummaryWriter(log_dir=str(log_dir))
    print(f"[Stage 2] TensorBoard → {log_dir}  (tensorboard --logdir runs/)", flush=True)
    print(f"[Stage 2] Scheduled sampling: ramps 0 → {ss_max_p:.1%} over first half of training", flush=True)

    student_model.train()
    losses: list[float] = []
    global_step = 0
    last_val_loss = float("nan")
    last_wer = float("nan")

    total_steps = epochs * len(train_loader)

    for epoch in range(epochs):
        print(f"\n{'='*55}", flush=True)
        print(f"[Stage 2] Epoch {epoch + 1} / {epochs}", flush=True)
        print(f"{'='*55}", flush=True)

        for batch in tqdm(train_loader, desc=f"[S2] Epoch {epoch+1}"):
            input_features = batch["input_features"].to(device)
            labels = batch["labels"].to(device)

            bos = torch.full(
                (labels.shape[0], 1),
                student_model.config.decoder_start_token_id,
                dtype=torch.long,
                device=device,
            )
            # Teacher-forced decoder input: [BOS, label_0, ..., label_{L-2}]
            decoder_input_ids = torch.cat([bos, labels[:, :-1].clamp(min=0)], dim=1)

            # ── Scheduled sampling ────────────────────────────────────────────
            # Ramp p from 0 → ss_max_p over first half of training, hold for second half
            current_p = ss_max_p * min(1.0, global_step / max(total_steps * 0.5, 1))

            decoder_input_ids = _build_mixed_decoder_input(
                student_model, input_features, decoder_input_ids, current_p, device
            )

            # ── Training forward ──────────────────────────────────────────────
            out = student_model(
                input_features=input_features,
                decoder_input_ids=decoder_input_ids,
            )
            loss = F.cross_entropy(
                out.logits.reshape(-1, out.logits.size(-1)),
                labels.reshape(-1),
                ignore_index=-100,
            )

            if not torch.isfinite(loss):
                print(f"  [S2] Non-finite loss at step {global_step} — skipping", flush=True)
                optimizer.zero_grad()
                global_step += 1
                continue

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(student_model.parameters(), 1.0)
            optimizer.step()
            if scheduler is not None:
                scheduler.step()

            losses.append(loss.item())
            writer.add_scalar("train/loss", loss.item(), global_step)
            writer.add_scalar("train/lr", optimizer.param_groups[0]["lr"], global_step)
            writer.add_scalar("train/ss_p", current_p, global_step)
            global_step += 1

            # ── stdout log ────────────────────────────────────────────────────
            if global_step % log_every == 0:
                parts = [
                    f"Step {global_step}",
                    f"loss {loss.item():.4f}",
                    f"ss_p {current_p:.2f}",
                ]
                if math.isfinite(last_val_loss):
                    parts.append(f"val_loss {last_val_loss:.4f}")
                if math.isfinite(last_wer):
                    parts.append(f"WER {last_wer*100:.1f}%")
                print("  [S2] " + " | ".join(parts), flush=True)

            # ── val loss (cheap) ──────────────────────────────────────────────
            if global_step % eval_every == 0:
                last_val_loss = compute_val_loss(student_model, val_loader, device)
                writer.add_scalar("val/loss", last_val_loss, global_step)
                writer.flush()
                print(
                    f"  [S2 Val] step {global_step} | val_loss {last_val_loss:.4f}",
                    flush=True,
                )

            # ── WER (expensive) ───────────────────────────────────────────────
            if processor is not None and global_step % wer_every == 0:
                wer = compute_wer(student_model, val_loader, processor, device, max_batches=10)
                if wer is not None:
                    last_wer = wer
                    writer.add_scalar("val/wer", wer, global_step)
                    writer.flush()
                    print(
                        f"  [S2 WER] step {global_step} | WER {wer*100:.1f}%",
                        flush=True,
                    )

        # ── Epoch end ─────────────────────────────────────────────────────────
        ckpt = checkpoint_dir / f"stage2_epoch_{epoch + 1}.pt"
        torch.save(student_model.state_dict(), ckpt)
        print(f"[Stage 2] Checkpoint → {ckpt}", flush=True)

        if processor is not None:
            wer = compute_wer(student_model, val_loader, processor, device, max_batches=20)
            if wer is not None:
                last_wer = wer
                writer.add_scalar("val/wer", wer, global_step)
                writer.flush()
                print(f"  [S2 Epoch WER] epoch {epoch+1} | WER {wer*100:.1f}%", flush=True)

    writer.close()
    return losses
